- name: 4.2.9 Ensure that the --event-qps argument is set to 0 or a level which ensures appropriate event capture
  lineinfile:
    path: /etc/kubernetes/kubelet-config.yaml
    regexp: '^eventRecordQPS'
    line: 'eventRecordQPS: 5'

