---
- name: 1.2.35 Ensure that the API Server only makes use of Strong Cryptographic Ciphers
  become: yes
  become_user: root
  lineinfile:
    path: /etc/kubernetes/manifests/kube-apiserver.yaml
    insertafter: "- kube-apiserver$"
    line: "    - --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_256_GCM_SHA384,TLS_RSA_WITH_AES_128_GCM_SHA256"
    firstmatch: yes
    state: present
