- name: 1.2.6 Ensure that the --kubelet-certificate-authority argument is set as appropriate
  block:
    - name: 1.2.6 check kubelet-certificate-authority flag
      command: grep --silent "kubelet-certificate-authority=" /etc/kubernetes/manifests/kube-apiserver.yaml
      register: kca_flag
      check_mode: no
      ignore_errors: yes
      changed_when: no
    
    - name: 1.2.6 add kubelet-certificate-authority flag
      replace:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regexp: '^(.*kubelet-client-certificate=.*)$'
        replace: '    - --kubelet-certificate-authority=/etc/kubernetes/ssl/ca.crt\n\1'
      when: kca_flag.rc != 0
