- name: 1.2.12 Ensure that the admission control plugin PodSecurityPolicy is set
  block:
    - name: test for line
      shell: grep "^.*--enable-admission-plugins=.*$" /etc/kubernetes/manifests/kube-apiserver.yaml | grep -c PodSecurityPolicy
      register: test_flag
      ignore_errors: yes

    - name: check for PodSecurityPolicy
      lineinfile:
        path: /etc/kubernetes/manifests/kube-apiserver.yaml
        regex: '^(.*--enable-admission-plugins=.*)$'
        line: '\1,PodSecurityPolicy'
        backrefs: yes
      when: test_flag.stdout == "0"
